"""xóa các cột trong bảng embedding_model_profiles

Revision ID: 0802b55c4dc8
Revises: 202605280001
Create Date: 2026-05-31 14:46:54.568119+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0802b55c4dc8'
down_revision: Union[str, None] = '202605280001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_providers_code_key'), 'ai_providers', type_='unique')
    op.drop_index(op.f('ix_ai_providers_code'), table_name='ai_providers')
    op.create_index(op.f('ix_ai_providers_code'), 'ai_providers', ['code'], unique=True)
    op.drop_constraint(op.f('platform_users_email_key'), 'platform_users', type_='unique')
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('platform_users_email_key'), 'platform_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ai_providers_code'), table_name='ai_providers')
    op.create_index(op.f('ix_ai_providers_code'), 'ai_providers', ['code'], unique=False)
    op.create_unique_constraint(op.f('ai_providers_code_key'), 'ai_providers', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
